### ISSUE TITLE
Remove quotes around title

### ISSUE THREAD

**Issue by Nordico-team** [Nordico-Tech/Travelbunny-Web#13]
Please delete quotes around the title and change them to Nordico.tech or Nordico
![image](https://user-images.githubusercontent.com/77929642/109291279-afe15980-7820-11eb-92ae-7e81116bf425.png)
to
![image](https://user-images.githubusercontent.com/77929642/109291511-f9ca3f80-7820-11eb-88a6-51590b19f223.png)

If this is an good issue please mark it as "Good first issue".
Tiago Rangel

**Comment by siigdev** [comment]
This will be done when the site is being hosted properly on our own domain. The deployment steps are currently being worked upon. Right now we are using redirection and this does now allow for inheriting title and url in the same way.

**Comment by tiagorangel2011** [comment]
Done
